server:
  port: 8100
  undertow:
    direct-buffers: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # ip-address:
    prefer-ip-address: true
spring:
  application:
    name: provider-server